we_meet_we_meet_User:
    type: rest
    prefix: /v1
    resource: "@WeMeetWeMeetBundle/Controller/UserController.php"
    name_prefix:  api_1_
    
we_meet_we_meet_Party:
    type: rest
    prefix: /v1
    resource: "@WeMeetWeMeetBundle/Controller/PartyController.php"
    name_prefix:  api_1_